### PR TITLE
Adding qr-code justify

### PR DESCRIPTION
**Pull request by esin**
Hi

We used your qrcode-terminal for our project, but we need to justify qr-code to center, so I made some addings and now create PR

Thank you

### CODE REVIEW

**Comment by dawndiy** [comment]
Thanks @esin 
It LGTM, but the 'stty' command can't be used on Windows, may be you can disable it when using Windows.

**Comment by esin** [comment]
@dawndiy I have update my PR
I've found Windows (Windows Server 2012 R2) for testing, than run qrcode-terminal and looks like escape characters from bash don't work fine in Windows
image

**Comment by dawndiy** [comment]
I create a issue for the bug here #2

**Comment by esin** [comment]
@dawndiy It's a good idea

Thank you!

**Pull request merged**
